### ISSUE TITLE
test game play

### ISSUE THREAD

**Issue by Arthinan660610807** [Arthinan660610807/Machine-learning#5]

**Comment by raffanids** [comment]
ที่ควรปรับปรุง
- มอนสเตอร์มีความเร็วที่เร็วเกินไปกว่าที่ผู้เล่นปกติจะเล่นได้ ควรปรับลดความเร็วของมอนสเตอร์ทุกตัวให้สอดคล้องกับวิธีการเล่น
- ระยะเวลา Delay ของกระสุนที่ยิงออกมามีมากเกินไปส่งผลให้กระสุนออกมาไม่สอดคล้องกับจังหวะการเคลื่อนไหวของผู้เล่น

คำแนะนำ
- ควรปรับลดความเร็วของมอนสเตอร์ทุกตัวให้สอดคล้องกับวิธีการเล่นที่ออกแบบมาใหม่
- ปรับ Delay ของกระสุนให้ลดลงมาจากเดิม 0.5-0.75 s เพื่อให้สอดคล้องกับการเคลื่อนไหวของผู้เล่น
