### ISSUE TITLE
ปรับความยากของเกม

### ISSUE THREAD

**Issue by Arthinan660610807** [Arthinan660610807/Machine-learning#6]

**Comment by patiphan24** [comment]
เนื่องจากการควบคุมด้วยการเคลื่อนไหวโดยใช้AIมีความยากกว่าการใช้ปุ่มกดผมเลยทำการปรับลดความยากของเกมโดยการลดความเร็วของ monter และได้เพิ่ม Delay ของการยิงให้มากขึ้นเพื่อคนผู้เล่นสามารถสนุกกับเกมแล้วผ่านด่านได้
